### ISSUE TITLE
semver crate doesn't compile with default features disabled in 1.0.1

### ISSUE THREAD

**Issue by NigelThorpe** [dtolnay/semver#244]
A simple `cargo check --no-default-features` from the 1.0.1 tag fails with:
```
   Compiling semver v1.0.1 (/home/nt/tmp2/semver)
error[E0433]: failed to resolve: use of undeclared type `Vec`
   --> src/impls.rs:152:27
    |
152 |         let comparators = Vec::from_iter(iter);
    |                           ^^^ not found in this scope
    |
help: consider importing one of these items
    |
1   | use alloc::vec::Vec;
    |
1   | use crate::Vec;
    |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
error: could not compile `semver`

To learn more, run the command again with --verbose.
```
Other simple repro: `cargo init; cargo add semver --no-default-features; cargo check`

Doesn't happen on the 1.0.0 tag. This probably doesn't get used much for this crate, but we hit this on a repository where we were trying to reduce feature use all over to speed up compiles.

**Comment by dtolnay** [comment]
Thanks &mdash; I've released 1.0.2. with a fix.
